"""Platform library for VN News Intelligence services."""

from news_platform.config import (
    get_lakehouse_catalog_name,
    get_lakehouse_warehouse_uri,
    get_topic_key,
    get_topic_name,
    load_pipeline_config,
    load_pipeline_definition,
    load_settings,
    load_sources,
)
from news_platform.contracts import (
    CURATED_TABLE_CONTRACTS,
    EVENT_CONTRACTS,
    EVENT_TOPIC_KEYS,
    ICEBERG_DEFAULT_PROPERTIES,
    TABLE_CONTRACTS,
    ArticleExtracted,
    ArticleFetched,
    ArticleFetchRequested,
    ArticleImage,
    ArticleTextBlock,
    FeedItemDiscovered,
    IcebergTableContract,
    NewsDlq,
    PipelineJobDefinition,
    PipelineOutputDefinition,
    SparkJobDefinition,
    TableField,
    TablePartition,
    event_json_schema,
    get_table_contract,
    parse_partition_expression,
)
from news_platform.ids import make_run_id, make_stable_id, normalize_article_url
from news_platform.storage import StorageLayout

__all__ = [
    "EVENT_CONTRACTS",
    "EVENT_TOPIC_KEYS",
    "CURATED_TABLE_CONTRACTS",
    "ICEBERG_DEFAULT_PROPERTIES",
    "TABLE_CONTRACTS",
    "ArticleExtracted",
    "ArticleFetched",
    "ArticleFetchRequested",
    "ArticleImage",
    "ArticleTextBlock",
    "FeedItemDiscovered",
    "IcebergTableContract",
    "NewsDlq",
    "PipelineJobDefinition",
    "PipelineOutputDefinition",
    "SparkJobDefinition",
    "TableField",
    "TablePartition",
    "StorageLayout",
    "event_json_schema",
    "get_table_contract",
    "get_lakehouse_catalog_name",
    "get_lakehouse_warehouse_uri",
    "get_topic_key",
    "get_topic_name",
    "load_settings",
    "load_sources",
    "load_pipeline_config",
    "load_pipeline_definition",
    "make_run_id",
    "make_stable_id",
    "normalize_article_url",
    "parse_partition_expression",
]
